### ISSUE TITLE
support Suricata/EVE flow/netflow records

### ISSUE THREAD

**Issue by inliniac** [jasonish/dumpy#1]
These records work currently, but simply like the alert records. However flow/netflow records contain a start and end time, so it should be possible to automagically get the proper time range (+ a margin for slight time drifts?)

**Comment by jasonish** [comment]
Done! At least its working for me.  It starts one second before the `start` and ends one second after the `end` if it exists. If no `end` exists, it'll only look for the following 60 seconds of the flow.

**Comment by jasonish** [comment]
You'll have to install from git though: `cargo install --git https://github.com/jasonish/dumpy`.
